jdk:
    vendor:
        name: Oracle-JDK
        version: ${java.version}
gradle:
    version: 8.7
    DSL: Kotlin
spring:
  application:
    name: RAG-Ollama
    version: 0.0.1-SNAPSHOT
    description: DEMO AI RAG project for using Local Models through Ollama
  output:
    ansi:
      enabled: always
  ai:
    ollama:
      chat:
        options:
          model: llama3
      embedding:
        options:
          model: llama3
ysy:
  ai:
    app:
      vectorStorePath: /tmp/vectorStore.json
      documentsToLoad:
        - classpath:/movies50.csv
